Record LTTng snapshot when latency higher than a threshold
When a request takes longer than the specified threshold (in ms), use
LTTng to record a snapshot of all kernel events in /tmp.

For now the snapshots are recorded locally (in /tmp), so the
lttng-consumerd requests appear in the iosnoop output every time we
record a snapshot, but it could be sent on the network to a remote
lttng-relayd.

Signed-off-by: Julien Desfossez <jdesfossez@efficios.com>

diff --git a/iosnoop b/iosnoop
--- a/iosnoop
+++ b/iosnoop
@@ -8,7 +8,7 @@
 # devices and their resulting performance. I/O completions can also be studied
 # event-by-event for debugging disk and controller I/O scheduling issues.
 #
-# USAGE: ./iosnoop [-hQst] [-d device] [-i iotype] [-p pid] [-n name] [duration]
+# USAGE: ./iosnoop [-hlQst] [-d device] [-i iotype] [-l ms] [-p pid] [-n name] [duration]
 #
 # Run "iosnoop -h" for full usage.
 #
@@ -59,14 +59,16 @@ bufsize_kb=4096
 opt_duration=0; duration=; opt_name=0; name=; opt_pid=0; pid=; ftext=
 opt_start=0; opt_end=0; opt_device=0; device=; opt_iotype=0; iotype=
 opt_queue=0
+opt_lttng=0
 trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
 function usage {
 	cat <<-END >&2
-	USAGE: iosnoop [-hQst] [-d device] [-i iotype] [-p PID] [-n name]
+	USAGE: iosnoop [-hQst] [-d device] [-i iotype] [-l ms] [-p PID] [-n name]
 	               [duration]
 	                 -d device       # device string (eg, "202,1)
 	                 -i iotype       # match type (eg, '*R*' for all reads)
+	                 -l ms           # record a LTTng snapshots when request time > ms
 	                 -n name         # process name to match on I/O issue
 	                 -p PID          # PID to match on I/O issue
 	                 -Q              # use queue insert as start time
@@ -107,6 +109,7 @@ function end {
 	fi
 	warn "echo > trace"
 	(( wroteflock )) && warn "rm $flock"
+	(( opt_lttng )) && destroy_lttng
 }
 
 function die {
@@ -122,12 +125,80 @@ function edie {
 	exit 1
 }
 
+function destroy_lttng()
+{
+	lttng destroy $SESSION_NAME >/dev/null
+	echo "Snapshots recorded in /tmp/$SESSION_NAME"
+}
+
+function setup_lttng()
+{
+	export SESSION_NAME="iosnoop-lttng-$RANDOM"
+
+	pgrep -u root lttng-sessiond >/dev/null
+	if test $? != 0; then
+		echo "Starting lttng-sessiond as root"
+		lttng-sessiond -d
+		if test $? != 0; then
+			edie
+		fi
+	fi
+
+	pgrep lttng-relayd >/dev/null
+	if test $? != 0; then
+		echo "Starting lttng-relayd as your current user, start manually if \
+	it fails"
+		lttng-relayd -d
+		if test $? != 0; then
+			edie
+		fi
+	fi
+
+	SUDO=""
+
+	# check if lttng command if in the path
+	# check if the user can execute the command (with sudo if not in tracing group)
+	# check if lttng-modules is installed
+	$SUDO lttng list -k | grep sched_switch >/dev/null
+	if test $? != 0; then
+		echo "Something went wrong executing \"$SUDO lttng list -k | grep sched_switch\", \
+	try to fix the problem manually and then start the script again"
+	fi
+
+	# if our random session name was already in use, add more randomness...
+	$SUDO lttng list | grep $SESSION_NAME
+	if test $? = 0; then
+		SESSION_NAME="$SESSION_NAME-$RANDOM"
+	fi
+	$SUDO lttng list | grep $SESSION_NAME
+	if test $? = 0; then
+		echo "Cannot create a random session name, something must be wrong"
+		exit 2
+	fi
+
+	#network: lttng create $SESSION_NAME --snapshot -U net://localhost >/dev/null
+	lttng create $SESSION_NAME --snapshot -o /tmp/$SESSION_NAME >/dev/null
+	[[ $? != 0 ]] && edie
+
+	lttng enable-channel -s $SESSION_NAME -k chan --subbuf-size 4M >/dev/null
+	[[ $? != 0 ]] && edie
+
+	lttng enable-event -s $SESSION_NAME -c chan -k -a >/dev/null
+	[[ $? != 0 ]] && edie
+	lttng add-context -s $SESSION_NAME -k -c chan -t pid -t procname >/dev/null
+	[[ $? != 0 ]] && edie
+
+	lttng start $SESSION_NAME >/dev/null
+	[[ $? != 0 ]] && edie
+}
+
 ### process options
-while getopts d:hi:n:p:Qst opt
+while getopts d:hi:l:n:p:Qst opt
 do
 	case $opt in
 	d)	opt_device=1; device=$OPTARG ;;
 	i)	opt_iotype=1; iotype=$OPTARG ;;
+	l)	opt_lttng=1 ms=$OPTARG ;;
 	n)	opt_name=1; name=$OPTARG ;;
 	p)	opt_pid=1; pid=$OPTARG ;;
 	Q)	opt_queue=1 ;;
@@ -209,6 +280,8 @@ fi
 printf "%-12.12s %-6s %-4s %-8s %-12s %-6s %8s\n" \
     "COMM" "PID" "TYPE" "DEV" "BLOCK" "BYTES" "LATms"
 
+(( opt_lttng )) && setup_lttng
+
 #
 # Determine output format. It may be one of the following (newest first):
 #           TASK-PID   CPU#  ||||    TIMESTAMP  FUNCTION
@@ -231,7 +304,7 @@ else
 	cat trace_pipe
 fi ) | $awk -v o=$offset -v opt_name=$opt_name -v name=$name \
     -v opt_duration=$opt_duration -v opt_start=$opt_start -v opt_end=$opt_end \
-    -v b_start=$b_start '
+    -v b_start=$b_start -v opt_lttng=$opt_lttng -v ms=$ms '
 	# common fields
 	$1 != "#" {
 		# task name can contain dashes
@@ -281,6 +354,8 @@ fi ) | $awk -v o=$offset -v opt_name=$opt_name -v name=$name \
 			    comm, pid, dir, dev, loc, nsec * 512, latency
 			if (!opt_duration)
 				fflush()
+			if (opt_lttng && latency > ms)
+				system("lttng snapshot record -s $SESSION_NAME")
 
 			delete starts[dev, loc]
 			delete comms[dev, loc]
